# Generated by Django 4.0.4 on 2022-04-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_post_head_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
